- type: job
  parent: CMSurvivor
  id: RMCSurvivorPattharsHawker
  name: rmc-job-name-survivor-hawker
  description: cm-job-description-survivor
  playTimeTracker: CMJobSurvivor
  startingGear: RMCGearSurvivorHawker
  spawnMenuRoleName: Hawker (Patthars Survivor)
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: RMCSkillPresetSurvivor
    - type: EquipSurvivorPreset
      preset: RMCSurvivorPresetCivilian
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage

- type: startingGear
  parent: RMCGearSurvivor
  id: RMCGearSurvivorHawker
  equipment:
    jumpsuit: RMCJumpsuitBlueWorkwear
    shoes: CMBootsGrey
    outerClothing: RMCChefApron
    mask: RMCMaskRebreather
