- type: job
  parent: CMSurvivor
  id: RMCSurvivorPattharsPizzaGalaxy
  name: rmc-job-name-survivor-pizza-galaxy
  description: cm-job-description-survivor
  startingGear: RMCGearSurvivorPattharsPizzaGalaxy
  spawnMenuRoleName: Pizza Galaxy Delivery Driver (Patthars Survivor)
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: RMCSkillPresetSurvivorPizzaGalaxyDriver
    - type: EquipSurvivorPreset
      preset: RMCGearSurvivorPresetCivilian
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
  useLoadoutOfJob: CMSurvivor # for inheritance

- type: startingGear
  parent: RMCGearSurvivorHybrisaPizzaGalaxy
  id: RMCGearSurvivorPattharsPizzaGalaxy
  equipment:
    outerClothing: RMCWEYARainCoat
    hands: RMCHandsLeatherBlack
    shoes: RMCBootsPMC
    mask: RMCMaskGasCivilian

