- type: job
  parent: CMSurvivor
  id: RMCSurvivorPattharsTukTukDriver
  name: rmc-job-name-survivor-tuktuk-driver
  description: cm-job-description-survivor
  playTimeTracker: CMJobSurvivor
  startingGear: RMCGearSurvivorTukTukDriver
  spawnMenuRoleName: Tuk Tuk Driver (Patthars Survivor)
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: RMCSkillPresetSurvivorTrucker
    - type: EquipSurvivorPreset
      preset: RMCSurvivorPresetTrucker
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage

- type: startingGear
  parent: RMCGearSurvivor
  id: RMCGearSurvivorTukTukDriver
  equipment:
    head: RMCHeadCapTruckerBlue
    jumpsuit: CMJumpsuitTShirtGray
    eyes: RMCSunglassesBigFake
    shoes: RMCShoesBlack
    outerClothing: RMCCoatBlueVest
    gloves: RMCHandsBlack # TODO RMC14: Replace with fingerless gloves
