
# Survivor skills

- type: entity
  id: RMCSkillPresetSurvivor
  name: Survivor
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillConstruction: 1
      RMCSkillEndurance: 2
      RMCSkillFireman: 1
      RMCSkillFirearms: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorResearcher
  name: Survivor Researcher
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillMedical: 3
      RMCSkillSurgery: 2
      RMCSkillResearch: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorDoctor
  name: Survivor Doctor
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillMedical: 3
      RMCSkillSurgery: 2
      RMCSkillFireman: 2

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorEngineer
  name: Survivor Engineer
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillEngineer: 2
      RMCSkillConstruction: 2
      RMCSkillVehicles: 1
      RMCSkillPowerLoader: 2

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorChaplain
  name: Survivor Chaplain
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillLeadership: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorGangLeader
  name: Survivor Gang Leader
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillCqc: 2
      RMCSkillLeadership: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorPrisoner
  name: Survivor Prisoner
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillCqc: 2
      RMCSkillMeleeWeapons: 1
      RMCSkillVehicles: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorTrucker
  name: Survivor Trucker
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillEngineer: 2
      RMCSkillConstruction: 2
      RMCSkillVehicles: 3

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorMiner
  name: Survivor Miner
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillEngineer: 1
      RMCSkillPowerLoader: 2
      RMCSkillVehicles: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorPizzaGalaxyDriver
  name: Survivor Pizza Galaxy Delivery Driver
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillVehicles: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorCommercialPilot
  name: Survivor Commercial Pilot
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillPilot: 2
      RMCSkillLeadership: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorParamedic
  name: Survivor Paramedic
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillMedical: 3
      RMCSkillSurgery: 2
      RMCSkillVehicles: 1
      RMCSkillFireman: 2

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorFireProtectionSpecialist
  name: Survivor Fire Protection Specialist
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillEngineer: 2
      RMCSkillMedical: 1
      RMCSkillFireman: 2
      RMCSkillVehicles: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorAirTrafficController
  name: Survivor Air Traffic Controller
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillLeadership: 1
      RMCSkillEngineer: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorNovarisExecutive
  name: Survivor Novaris Executive
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillEngineer: 2

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorHalcyonExecutive
  name: Survivor Halcyon Executive
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillFirearms: 2

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorAvantExecutive
  name: Survivor Avant Executive
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillMedical: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorAvantDoctor
  name: Survivor Avant Doctor
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
        RMCSkillMedical: 3
        RMCSkillSurgery: 2

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorWestonYamadaOnsiteMedic
  name: Survivor Weston-Yamada Onsite Medic
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
        RMCSkillMedical: 3
        RMCSkillSurgery: 2
        RMCSkillVehicles: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorBackAlleySurgeon
  name: Survivor back-alley surgeon
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
        RMCSkillMedical: 2
        RMCSkillSurgery: 3
        RMCSkillVehicles: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorCargoWorker
  name: Survivor Cargo Worker
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillEngineer: 2
      RMCSkillPowerLoader: 2
      RMCSkillConstruction: 2
      RMCSkillVehicles: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorTartarusMiner
  name: Survivor Tartarus Miner
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillEngineer: 2
      RMCSkillPowerLoader: 1
      RMCSkillConstruction: 2
      RMCSkillVehicles: 2

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorTartarusMiningSurveyor
  name: Survivor Tartarus Mining Surveyor
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillConstruction: 1
      RMCSkillMedical: 2
      RMCSkillSurgery: 1
      RMCSkillResearch: 1
      RMCSkillEngineer: 2

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorAvantBiomedicalScientist
  name: Survivor Avant Biomedical Scientist
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillMedical: 3
      RMCSkillSurgery: 1
      RMCSkillResearch: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorHalcyonGunsmith
  name: Survivor Halcyon Gunsmith
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillMedical: 2
      RMCSkillSurgery: 1
      RMCSkillResearch: 1
      RMCSkillFirearms: 2

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorTSEPAInspector
  name: Survivor TSEPA Inspector
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillEngineer: 1
      RMCSkillMeleeWeapons: 1
      RMCSkillConstruction: 2
      RMCSkillMedical: 2
      RMCSkillEndurance: 3
      RMCSkillCqc: 3
      RMCSkillFirearms: 2
      RMCSkillFireman: 2
      RMCSkillLeadership: 2
